### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by NektoUa** [NektoUa/homepage-2#2]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by NektoUa** [comment]
Я думаю ми можемо написати гарне інтро

**Comment by NektoUa2** [comment]
Я з тобою не згоден. Він сам його собі вже склав.

**Comment by NektoUa** [comment]
надива інтро в інтернеті і вставив
