### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by NektoUa** [NektoUa/homepage-2#4]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by NektoUa2** [comment]
<div class="ten wide column">
                            <h3>experience</h3>
                            <h5>2021</h5>
                            <p>Lost everything...</p>

                            <h5>2020</h5>
                            <p><b>Keep America Great!</b> We almost won!</p>

                            <h5>2017</h5>
                            <p>Became <b>45th president</b> of the United States</p>

                            <h5>2016</h5>
                            <p> Won election race with 77 votes more than Clinton, yippe-kee-yay!</p>

                            <h5>2015</h5>
                            <p> Became the most important Republican nominating for presidential election run</p>

                            <h5>2009</h5>
                            <p>Changed my mind and became Republican again</p>

                            <h5>2005</h5>
                            <p>Started <i>Trump University</i> with Michael Sexton and Jonathan Spitalny: no grades,
                                certificates
                                and other bureaucracy, but program offered courses in real estate, asset management
                                entrepreneurship, and wealth creation. <b>98% students!!!</b> gave positive reviews
                                while
                                studying,
                                however some of these ungrateful gringos filed lawsuits against Trump University after
                                the
                                course. I had to pay $25 million to settle that...</p>

                            <h5>2002</h5>
                            <p> Acquired the former Hotel Delmonico, which was renovated and reopened in 2004 as the
                                Trump
                                Park Avenue. I sure do like my surname!</p>

                            <h5>2001</h5>
                            <p> Completed <i>Trump World Tower</i> and joined the Democratic Party</p>

                            <h5>1999</h5>
                            <p> Started buying golf courses. They are very cheap, I have 18 of them now in USA and
                                abroad!
                                Also switched to the Reform Party that year</p>

                            <h5>1997</h5>
                            <p> Began a multi-building development along the Hudson River, which was named Trump Place.
                                Me
                                and the other investors sold our shares for $1.8 billion and that was then the biggest
                                residential sale in the history of New York City</p>

                            <h5>1996</h5>
                            <p> Acquired the Bank of Manhattan Trust Building, which was a vacant seventy-one story
                                skyscraper on Wall Street. After an extensive renovation, the high-rise was renamed the
                                <i>Trump Building</i></p>

                            <h5>1994</h5>
                            <p> Refurbished the Gulf and Western Building on Columbus Circle, turned it into a 44-story
                                luxury property known as <i>Trump International Hotel and Tower</i></p>

                            <h5>1989 ― 1992</h5>
                            <p>Ran a second hand airline called Trump Shuttle. What a waste of money, I had to sell it,
                                now
                                it is American Airlines Shuttle, btw</p>

                            <h5>1989, 1990</h5>
                            <p>Learned about Tour de France and decided to hold my very own Tour de Trump. Is America
                                not
                                great enough for that cycling competition?</p>

                            <h5>1988</h5>
                            <p>Acquired the Plaza Hotel in Manhattan for $407 million, invested $50 million to restore
                                the
                                building and boosted it from three-star to four-star hotel (I called it "the Mona Lisa"
                                and
                                sold it for a lot of cash in 1995)</p>

                            <h5>1987</h5>
                            <p>Registered as a Republican</p>

                            <h5>1985</h5>
                            <p>I bought the Mar-a-Lago estate in Palm Beach and turned it into a private club.You can
                                join
                                if you pay $200K initiation fee (and there is another annual fee for members, it is very
                                expensive to be rich). That year I also opened a casino called Trump Castle. My wife
                                Ivana
                                became a manager, because she is another Trump!</p>

                            <h5>1983</h5>
                            <p>I purchased New Jersey Generals, an American football team. I changed team's play
                                schedule
                                and filed an antitrust lawsuit against United States Football League, so NJG are not
                                doing
                                so good now, but back then they were great!</p>

                            <h5>1980</h5>
                            <p>Started developing the Trump Tower skyscraper in Manhattan, I payed a crew of
                                undocumented
                                Polish workers to demolish the historic Bonwit Teller store, including art deco
                                features.
                                All this to make architectural critic Paul Goldberger say in 1983 that the tower's
                                atrium is
                                "the most pleasant interior public space to be completed in New York in some years". At
                                the
                                same time I also started a repair job on the Wollman Rink in Central Park and completed
                                the
                                work in three months for $1.95 million, which was $775,000 less than the initial budget!
                            </p>

                            <h5>1978</h5>
                            <p>Purchased a 50 percent stake in the derelict Commodore Hotel and turned it
                                into the Grand
                                Hyatt Hotel in 2 years of remodeling</p>

                            <h5>1971</h5>
                            <p>Was promoted to president of the company and renamed it The Trump Organization</p>

                            <h5>1968</h5>
                            <p>Began my career at my father's real estate development company, <i>Elizabeth Trump &
                                    Son</i></p>

                            <h5>1946</h5>
                            <p>I was born</p>

**Comment by NektoUa** [comment]
додано до основного розділу
